---
- hosts: localhost 
  connection: local
  become: true

  tasks:
  - name: install packages
    become: true
    become_method: sudo
    package:
      name:
        - htop
        - tmux
        - vim
        - neovim
        - neofetch

  - name: copy wallpaper file
    copy:
      src: files/ansible_wallpaper.jpg
      dest: /usr/share/backgrounds/ansible_wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: juanjo
    dconf:
      key: "/org/gnome/desktop/backgrounds/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible_wallpaper.jpg'"

  - name: set wallpaper position
    become_user: juanjo
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .zshrc file
    copy:
      src: files/zshrc
      dest: /home/juanjo/.zshrc
      owner: juanjo
      group: juanjo
