---
- hosts: localhost 
  connection: local
  become: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"

  tasks:
  - name: install packages
    become: true
    become_method: sudo
    package:
      name:
        - python3-psutil
        - htop
        - tmux
        - vim
        - neovim
        - neofetch
        - zsh
        - curl
        - cmake
        - pkg-config
        - libfreetype6-dev
        - libfontconfig1-dev
        - libxcb-xfixes0-dev
        - fzf

  - name: create NeoVIM folder
    file:
      path: "{{ home }}/.config/nvim"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: copy Alias file
    copy:
      src: files/alias
      dest: "{{ home }}/.alias"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: copy PowerLevel10k
    copy:
      src: files/p10k
      dest: "{{ home }}/.p10k.zsh"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: copy VIM config
    copy:
      src: files/vimrc
      dest: "{{ home }}/.vimrc"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: copy NeoVIM config
    copy:
      src: files/neovim
      dest: "{{ home }}/.config/nvim/init.vim"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: clone ohmyzsh
    git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{ home }}/git/ohmyzsh"
      update: yes

  - name: install ohmyzsh
    shell:
      chdir: "{{ home }}/git/ohmyzsh/tools"
      executable: "{{ home }}/git/ohmyzsh/tools/install.sh"
      cmd: install.sh

  - name: clone powerlevel10k
    git:
      clone: yes
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
      update: yes

  - name: copy .zshrc file
    copy:
      src: files/zshrc
      dest: "{{ home }}/.zshrc"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: copy tmux config
    copy:
      src: files/tmux
      dest: "{{ home }}/.tmux.conf"
      owner: "{{ user }}"
      group: "{{ user }}"


  - name: copy wallpaper file
    copy:
      src: files/ansible_wallpaper.jpg
      dest: /usr/share/backgrounds/ansible_wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: juanjo
    dconf:
      key: "/org/gnome/desktop/backgrounds/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible_wallpaper.jpg'"

  - name: set wallpaper position
    become_user: juanjo
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: add ansible user
    user:
      name: ansible
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoers_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/juanjodarko/ansible_desktop.git 

